name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install  # or use `npm ci` if you have a lock file and prefer a clean install

      - name: Run Tests
        run: npm test
        id: tests  # Assign an id to this step to reference its outcome later

      - name: Build the Docker image
        if: success()  # This step will only run if all previous steps were successful
        run: docker build . --file Dockerfile --tag vlottetonny/epubtransmitterbackendgithub:${{ github.sha }}

      - name: Login to Docker Hub
        if: success()  # This step will only run if all previous steps were successful
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Push the Docker image
        if: success()  # This step will only run if all previous steps were successful
        run: docker push vlottetonny/epubtransmitterbackendgithub:${{ github.sha }}
